# Generated by Django 2.1.1 on 2019-08-09 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_create_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='create_post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Create_Post',
        ),
    ]
